name: autorelease

on:
  push:
    branches:
      - master

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Compute the new version
        id: version
        run: scripts/compute-version.rb >> $GITHUB_OUTPUT
      - name: Create release ${{ steps.version.outputs.version }}
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.version.outputs.version }}

